on: [push, pull_request]
name: py315-tests
concurrency:
  # Cancel build if a new one starts, but don't interrupt all jobs on the first
  # failure.
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:

  # Run tests on Linux, macOS, Windows
  tests:
    name: "${{ matrix.os }}, ${{ matrix.arch }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, arch: x86_64 }
          - { os: ubuntu-24.04-arm, arch: aarch64 }
          - { os: macos-15, arch: x86_64 }
          - { os: macos-15, arch: arm64 }
          - { os: windows-2025, arch: AMD64 }
          - { os: windows-11-arm, arch: ARM64 }
    steps:
      - uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.15-dev'

      - name: Install psutil including test deps
        run: |
          python -m pip install .[test]

      - name: Run tests
        run: |
          # Same as in Makefile's `test` target
          cd tests
          python -m pytest . --ignore=tests/test_memleaks.py
